export const PRODUCT_CONFIG = {
  name: "ELETRODARA AETHER",
  codename: "CHRONOS // BATCH 01",
  subtitle: "Apex Clean Energy Core & Digital Metering",
  tagline: "O Maior Desconto de Energia do Brasil. Sem Obras. Sem Placas. 100% Legal.",
  whatsappNumber: "5554997143102",
  phoneFormatted: "(54) 99714-3102",
  cnpj: "61.326.080/0001-64",
  headquarters: "Parque Tecnológico TecnoUCS — Universidade de Caxias do Sul / RS",
  
  // Custom GLTF / GLB model configuration
  // Set modelPath to '/models/my-product.glb' to replace the procedural assembly with your custom 3D model
  modelPath: null,

  finishes: {
    obsidian: {
      id: "obsidian",
      name: "Matte Obsidian Titanium",
      color: "#18191c",
      metalness: 0.95,
      roughness: 0.22,
      clearcoat: 0.3,
      accentGlow: "#22c55e",
      previewHex: "#18191c",
    },
    silver: {
      id: "silver",
      name: "Raw Aerospace Silver",
      color: "#d4d4d8",
      metalness: 0.98,
      roughness: 0.14,
      clearcoat: 0.8,
      accentGlow: "#4ade80",
      previewHex: "#d4d4d8",
    },
    copper: {
      id: "copper",
      name: "Cyber Amber & Carbon",
      color: "#c2410c",
      metalness: 0.88,
      roughness: 0.25,
      clearcoat: 0.6,
      accentGlow: "#f59e0b",
      previewHex: "#c2410c",
    },
    ceramic: {
      id: "ceramic",
      name: "Arctic Technical Ceramic",
      color: "#f8fafc",
      metalness: 0.15,
      roughness: 0.04,
      clearcoat: 1.0,
      accentGlow: "#22c55e",
      previewHex: "#f8fafc",
    },
  },

  hotspots: [
    {
      id: "telemetry",
      title: "Telemetria Digital Bidirecional",
      category: "SMART GRID 2.0",
      description: "Medição de consumo 100% digital homologada pela ANEEL. Não altera seus cabos nem seu medidor físico.",
      position: [0, 1.4, 0.4],
      metric: "LATÊNCIA 0.4s",
      badge: "RESOLUÇÃO ANEEL",
    },
    {
      id: "solar_core",
      title: "Célula de Compensação Solar",
      category: "GERAÇÃO DISTRIBUÍDA",
      description: "Injeção contínua de créditos limpos gerados em usinas solares de grande porte. Abatimento de 20% a 25% na fatura.",
      position: [0.8, 0, 0],
      metric: "DESCONTO FIXO",
      badge: "LEI FEDERAL 14.300",
    },
    {
      id: "chassis",
      title: "Arquitetura Monolítica Sem Obras",
      category: "ZERO HARDWARE NO LOCAL",
      description: "Toda a geração ocorre nas usinas parceiras. Você não precisa instalar placas no telhado, fazer reformas ou furar paredes.",
      position: [-0.9, -0.6, 0.3],
      metric: "0 R$ INVESTIMENTO",
      badge: "PLUG & PLAY",
    },
  ],

  specs: [
    { label: "Marco Regulatório", value: "Lei Federal 14.300/2022" },
    { label: "Homologação", value: "Agência Nacional de Energia Elétrica (ANEEL)" },
    { label: "Custo de Adesão / Mensalidade", value: "R$ 0,00 (Gratuito)" },
    { label: "Obras ou Instalação", value: "Zero (100% Digital via Créditos)" },
    { label: "Desconto Médio Garantido", value: "20% a 25% na Fatura" },
    { label: "Fidelidade Obrigatória", value: "Nenhuma (Cancele a qualquer momento)" },
    { label: "Risco de Corte de Energia", value: "Zero (Concessionária local mantida)" },
    { label: "Segurança de Dados", value: "Conformidade LGPD & Criptografia 256-bit" },
    { label: "Base Operacional", value: "TecnoUCS — Caxias do Sul / RS" },
    { label: "CNPJ", value: "61.326.080/0001-64" },
  ],
};
